# Generated by Django 4.1.5 on 2023-04-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unihub", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="is_club_creator",),
    ]
