# Generated by Django 4.1.5 on 2023-04-09 06:54

from django.db import migrations
from django.contrib.auth.models import Group


def create_club_member_group(apps, schema_editor):
    Group.objects.get_or_create(name='club_member')


class Migration(migrations.Migration):
    dependencies = [
        ('unihub', '0002_remove_userprofile_is_club_creator'),
    ]

    operations = [
        migrations.RunPython(create_club_member_group),
    ]
