# Generated by Django 4.1.5 on 2023-04-12 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("unihub", "0004_create_club_admin_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_clubs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
