# Generated by Django 4.1.5 on 2023-04-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unihub", "0006_clubmember_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_image",
            field=models.ImageField(blank=True, null=True, upload_to="user_images/"),
        ),
    ]
