# Generated by Django 4.1.5 on 2023-04-21 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("unihub", "0007_alter_userprofile_options_userprofile_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubevent",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
